# Generated by Django 5.0.14 on 2026-04-30 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('nasa', 'NASA APOD'), ('weather', 'OpenWeather'), ('movie', 'TMDB')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('content_url', models.URLField(blank=True, max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('published_date', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Aggregated Content',
                'verbose_name_plural': 'Aggregated Contents',
                'db_table': 'aggregated_content',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['source', '-published_date'], name='aggregated__source_d2799f_idx'), models.Index(fields=['-fetched_at'], name='aggregated__fetched_77aaa5_idx')],
            },
        ),
    ]
